### ISSUE TITLE
problem with portal gun

### ISSUE THREAD

**Issue by Bounceysteve99** [Mee12345/GMod-Seamless-Portals#10]
[ERROR] lua/weapons/mee_swep.lua:70: attempt to call method 'LinkPortal' (a nil value)
  1. unknown - lua/weapons/mee_swep.lua:70

**Comment by Mee12345** [comment]
did you update all of the lua…? That shouldn’t be happening

maybe I forgot a check?

**Comment by Bounceysteve99** [comment]
turns out i was installing it in lua and i had two conflicting versions in lua and addons
