### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by MarcusKubis9** [Mee12345/GMod-Seamless-Portals#12]
I have been wanting to try this mod out for a while but I have no idea how to install it
if you could give a quick tutorial that would be amazing!

**Comment by KewlKris** [comment]
bro it's easy clone the repository and then put the whole folder in garrysmod/addons

**Comment by Bounceysteve99** [comment]
addons folder doesn't work for me, i have to put it in garrysmod/lua
