### ISSUE TITLE
`git clone`ing this to `garrysmod/addons` does nothing

### ISSUE THREAD

**Issue by TheAwesome98-Real** [Mee12345/GMod-Seamless-Portals#15]

**Comment by Fafy2801** [comment]
works for me, are you doing `git clone https://github.com/Mee12345/GMod-Seamless-Portals.git` on your `addons` folder?

**Comment by NimBlemations** [comment]
Did it not make a folder for the lua folder to reside in or something? I am confused.

**Comment by TheAwesome98-Real** [comment]
> works for me, are you doing `git clone https://github.com/Mee12345/GMod-Seamless-Portals.git` on your `addons` folder?

yep

**Comment by TheAwesome98-Real** [comment]
ok so it was the small letters
