### ISSUE TITLE
doesn't work with pp_stereoscopy 1

### ISSUE THREAD

**Issue by CapsAdmin** [Mee12345/GMod-Seamless-Portals#16]
(maybe you already know this and or it's not a priority)

**Comment by CapsAdmin** [comment]
right, so the problem is that stereoscopy overrides the hook

https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/postprocess/stereoscopy.lua#L49

I wonder then if you could use some other hook, but RenderScene sounds like it makes sense here.

**Comment by WasabiThumb** [comment]
For whatever reason, the two render.RenderView calls that the stereoscopy effect uses do not call their own RenderView, which they definitely should in my experience. Could the RenderScene calls potentially be moved to PostRender?

**Comment by WasabiThumb** [comment]
Looking at it, the only place that RenderScene is used here is when the portals are being drawn. Realistically they should be in DrawMonitors anyways, so I will move it there and let you know how it goes.

**Comment by WasabiThumb** [comment]
I wanted to reply when I found something servicable but it was just issue after issue. First of all, DrawMonitors is apparently broken according to the wiki and second of all, any other hook didn't work. Especially since it introduced some fun infinite recursion issues, which I could not solve satisfyingly.

**Comment by Mee12345** [comment]
yeah, sounds about right

what did the safespace and tardis addon do? I dont think they have this issue

**Comment by WasabiThumb** [comment]
Like I said, RenderView *should* definitely be calling RenderScene, but for whatever reason, the ones used in the stereoscopy effect do not. If they did, they would cause an infinite loop, but I have no idea where this behavior is being turned off

**Comment by Mee12345** [comment]
eh, it doesnt matter either way.. nobody uses it anyway

**Comment by Mee12345** [comment]
this started working for some reason, I have no idea why, I guess I changed around some code at some point and it magically fixed itself
