### ISSUE TITLE
[Bug] Having only one portal in gm_construct_10 does... this

### ISSUE THREAD

**Issue by GordonFreakman** [Mee12345/GMod-Seamless-Portals#20]
![image](https://user-images.githubusercontent.com/75632358/156282444-7f2ebc26-0c01-4805-ad15-888527755730.png)

**Comment by Mee12345** [comment]
um.. the script error details would be nice to have

**Comment by GordonFreakman** [comment]
sorry, i'm newer to issues, anyways here's the errors im getting

[gmod-seamless-portals-main] addons/gmod-seamless-portals-main/lua/autorun/server/sv_prop_teleport.lua:58: attempt to index local 'closestPortal' (a nil value)
  1. v - addons/gmod-seamless-portals-main/lua/autorun/server/sv_prop_teleport.lua:58
   2. unknown - lua/includes/modules/hook.lua:96 (x35)

**Comment by Mee12345** [comment]
k ty

**Comment by Mee12345** [comment]
this is sorta fixed, i will probably rewrite the prop code at some point
