### ISSUE TITLE
High velocity breaks wall portals

### ISSUE THREAD

**Issue by WasabiThumb** [Mee12345/GMod-Seamless-Portals#24]
NOTE: I observed this in singleplayer mode while on the map gm_bigcity_improved, and it's entirely possible that this issue doesn't exist elsewhere.

For me, anything faster than a leisurely stroll through a wall portal makes me bonk against it. This is somewhat unfortunate because when attempting a portal fling you lose all your velocity when going through a portal.

Apologies if you already know about this problem. I can provide video if necessary

**Comment by Mee12345** [comment]
detouring traceline may be impacting this..

the way I check if a player is valid to go through a portal is using a trace, which is then detoured..

**Comment by WasabiThumb** [comment]
Maybe. I really thought I had this issue before even making that code but I could be mistaken. I'll figure it out later

**Comment by Mee12345** [comment]
I don’t have any problem with it so… idk

**Comment by WasabiThumb** [comment]
Yeah that is the plan. Will let you know, if it turns out to be a problem with my changes then I'll close the issue and try to fix them too

**Comment by WasabiThumb** [comment]
Okay, it is a problem with my PR. I'll try to be more careful in the future, not sure how I missed that.
