### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Edcaaaa4gy53** [Mee12345/GMod-Seamless-Portals#26]
how do i install??? i need help

**Comment by WasabiThumb** [comment]
First go into your addons directory. That will be `<library folder>/steamapps/common/GarrysMod/garrysmod/addons`. Inside of there, put the addon folder. If you don't have git installed, then you can download the ZIP (top right on the main page) and extract the folder into there. If you do have git installed, you can simply do `git clone https://github.com/Mee12345/GMod-Seamless-Portals.git` inside of the addons folder.

After you've done either of those things, you should have a folder called GMod-Seamless-Portals inside of your "addons" folder. GMod doesn't like special characters and capital letters, so rename it to something like `seamless_portals`.

Assuming this works, make sure to close the issue by pressing the button at the bottom of the thread.

**Comment by WasabiThumb** [comment]
Click [here](https://github.com/Mee12345/GMod-Seamless-Portals/archive/refs/heads/main.zip) if you're struggling with finding the zip

**Comment by Mee12345** [comment]
should release to workshop in a couple days anyway

**Comment by Edcaaaa4gy53** [comment]
> git clone https://github.com/Mee12345/GMod-Seamless-Portals.git

i dont get it what the git clone https://github.com/Mee12345/GMod-Seamless-Portals.git ???? where??? also when i added the mod to addons folder and renamed its still not appearing
