### ISSUE TITLE
Not able to see through portals

### ISSUE THREAD

**Issue by RobinRattus** [Mee12345/GMod-Seamless-Portals#32]
If you place 2 portals using the portal gun, change their size to 2x or more then you wont be able to see through them anymore. (I think this is because the middle of the portal is now in the wall)

I made a video that shows the bug
https://www.youtube.com/watch?v=B1Za0ks473M

**Comment by WasabiThumb** [comment]
The portal resizer scales in the Z direction by the same amount as X, making portals strangely thick. I feel like they should work like the plastic plate props: fixed width and many sizes. That's how I implemented it in the portal creator tool (pending merge)

**Comment by Mee12345** [comment]
will fix this
