### ISSUE TITLE
Client-side traces do not hit the portal

### ISSUE THREAD

**Issue by dvdvideo1234** [Mee12345/GMod-Seamless-Portals#43]
Hello,

Consider the following code:
```lua
-- Configuring the trace
gtTRACE = {}
gtTRACE.mask == MASK_ALL
gtTRACE.funct == SeamlessPortals.TraceLine
gtTRACE.collisiongroup == COLLISION_GROUP_NONE

print(gtTRACE.mask == MASK_ALL,
      gtTRACE.funct == SeamlessPortals.TraceLine,
      gtTRACE.collisiongroup == COLLISION_GROUP_NONE)

-- Running the trace
local tr = gtTRACE.funct(gtTRACE)
-- Exctracting trace result
local target, iteration = tr.Entity, (tonumber(iteration) or 0) + 1
local ok, act = (target and target:IsValid()), target 
-- Print trace result
print(iteration, ok, act, target)
```

What the game prints:
```lua
SERVER
true	true	true
100	true	seamless_portal	Entity [358][seamless_portal]
true	true	true
99	true	seamless_portal	Entity [358][seamless_portal]
true	true	true
98	true	seamless_portal	Entity [358][seamless_portal]
CLIENT
true	true	true
97	false	nil	Entity [0][worldspawn]
true	true	true
100	false	nil	Entity [0][worldspawn]
true	true	true
100	false	nil	Entity [0][worldspawn]
```

**Comment by dvdvideo1234** [comment]
Adding this has the same effect `gtTRACE.collisiongroup = (COLLISION_GROUP_WORLD)` according to the wiki https://wiki.facepunch.com/gmod/Structures/Trace

**Comment by dvdvideo1234** [comment]
Both `base` and `x64` branches work the same

**Comment by dvdvideo1234** [comment]
The workshop version appears not to have this issue. Probably the WS version is a bit forward from github, @Mee12345

**Comment by dvdvideo1234** [comment]
This happens again. This time with the WS version:
```lua

    LaserLib.DrawPoint(trace.HitPos)

    LaserLib.Call(2, function()
      print()
      print("--------START----------")
      local t = table.Copy(gtTRACE)
      t.funct = (SeamlessPortals.TraceLine == gtTRACE.funct) and "SeamlessPortals.TraceLine" or "util.TraceLine"
      PrintTable(t)
      print("--------FINISH----------")
      PrintTable(trace)
    end)

--------START----------
collisiongroup	=	0 -- COLLISION_GROUP_NONE
endpos	=	-13076.123047 23832.986328 3482.639648
filter	=	Entity [680][gmod_laser]
funct	=	SeamlessPortals.TraceLine
ignoreworld	=	false
mask	=	4294967295 -- MASK_ALL
maxs	=	0.000000 0.000000 0.000000
mins	=	0.000000 0.000000 0.000000
start	=	-3535.195801 1057.716919 -423.467102
--------FINISH----------
AllSolid	=	false
Contents	=	1
DispFlags	=	0
Entity	=	Entity [0][worldspawn] -- Passes trough portal and hits the wall behind it
Fraction	=	0.025235800072551
FractionLeftSolid	=	0
Hit	=	true
HitBox	=	0
HitGroup	=	0
HitNoDraw	=	false
HitNonWorld	=	false
HitNormal	=	1.000000 0.000000 0.000000
HitPos	=	-3775.968750 1632.468994 -324.893372
HitSky	=	false
HitTexture	=	PLASTER/PLASTERWALL016A -- Map wall
HitWorld	=	true
LengthBS	=	25000
LengthFR	=	630.89500181377
LengthLS	=	0
MatType	=	68
Normal	=	-0.381637 0.911011 0.156244
PhysicsBone	=	0
StartPos	=	-3535.195801 1057.716919 -423.467102
StartSolid	=	false
SurfaceFlags	=	0
SurfaceProps	=	47
```
 Also it seems that some functions are also changed:
1.  `SP:ExitPortal()` becomes `ent:GetExitPortal()` server side
2. `ent:GetExitSize()` becomes `ent:GetSize()` both realms
 
![20230305103554_1](https://user-images.githubusercontent.com/9112662/222950535-7f862a01-5760-45a5-a7c6-99e38470f6d0.jpg)

**Comment by Mee12345** [comment]
yeah I see why.. ok so on the client in singleplayer the physics mesh of the portals is not initialized so that bullets travel through instead of hitting it (thank garry for making the bullet hook predicted)

im gonna see if I can initialize the physics object but add a flag on the client that lets bullets pass through it.. that should fix the issue

**Comment by dvdvideo1234** [comment]
Yeah, I recall it used to hit it, so it makes sense if something got changed :)

**Comment by Mee12345** [comment]
I pushed a fix, tell me if you experience any perf changes or anything.. seems to work for me

ill update workshop once you confirm it works

**Comment by dvdvideo1234** [comment]
Yep, this fixes it!

![20230307224256_1](https://user-images.githubusercontent.com/9112662/223547962-8d0224f7-29e1-481f-badd-768236f5a30e.jpg)


Made sure I am also not using the WS version
![image](https://user-images.githubusercontent.com/9112662/223548142-9793c652-5ecb-4e20-aace-d9ad8e66ef6a.png)
![image](https://user-images.githubusercontent.com/9112662/223548092-b668b872-a17a-4b26-9800-7b87ec763110.png)
