### ISSUE TITLE
error

### ISSUE THREAD

**Issue by FarikLoL** [Mee12345/GMod-Seamless-Portals#7]
[gmod-seamless-portals-main] addons/gmod-seamless-portals-main/lua/autorun/sh_portal_movement.lua:14: attempt to perform arithmetic on local 'finalVel' (a nil value)
  1. updateCalcViews - addons/gmod-seamless-portals-main/lua/autorun/sh_portal_movement.lua:14
   2. func - addons/gmod-seamless-portals-main/lua/autorun/sh_portal_movement.lua:56
    3. unknown - lua/includes/extensions/net.lua:33

**Comment by Agent-11** [comment]
Are you running it on a local server?

**Comment by FarikLoL** [comment]
Yes

**Comment by FarikLoL** [comment]
> Are you running it on a local server?
Yes

**Comment by FarikLoL** [comment]
> Are you running it on a local server?

Yes

**Comment by Mee12345** [comment]
this is fixed, next push shouldn't have this issue
