### ISSUE TITLE
Screen turns white when hovering over the portals with the cursor in the "C" menu

### ISSUE THREAD

**Issue by Flufiakojot** [Mee12345/GMod-Seamless-Portals#9]
## Flashing lights warning!

https://user-images.githubusercontent.com/89755606/155391158-f1b1b45c-63ce-4e8e-977f-5297c7ee6446.mp4

I have disabled all of the workshop addons, I do not think the external addons are affecting this.

**Comment by Mee12345** [comment]
oh jeez, that needs to be fixed right away before people get seizures 
I think I know a fix that will work..

**Comment by Mee12345** [comment]
aight this is fixed
